default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: '123'

development:
  <<: *default
  database: library_development

test:
  <<: *default
  database: library_test

production:
  <<: *default
  database: library_production
  username: library
  password: <%= ENV["LIBRARY_DATABASE_PASSWORD"] %>